language: node_js
sudo: false

env:
  - SENECA_VER=senecajs/seneca
  - SENECA_VER=plugin

node_js:
  - '11'
  - '10'
  - '8'

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls